import {
  COLORS,
  FONT_SIZE,
  FONT_WEIGHT,
  RADIUS,
  SHADOWS,
  SPACING,
} from '@/constants/theme'
import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  container: {
    backgroundColor: COLORS.background,
    flex: 1,
  },
  content: {
    gap: SPACING[4],
    minHeight: '100%',
    overflow: 'hidden',
    padding: SPACING[4],
    paddingBottom: SPACING[8],
    paddingHorizontal: SPACING[6],
    paddingTop: SPACING[10],
  },
  backgroundCircleTop: {
    backgroundColor: COLORS.primaryLight,
    borderRadius: 130,
    height: 260,
    position: 'absolute',
    right: -126,
    top: -116,
    width: 260,
  },
  backgroundCircleBottom: {
    backgroundColor: COLORS.secondaryLight,
    borderRadius: 140,
    bottom: -112,
    height: 280,
    left: -148,
    position: 'absolute',
    width: 280,
  },
  header: {
    alignItems: 'center',
    gap: SPACING[2],
  },
  logo: {
    height: 64,
    resizeMode: 'contain',
    width: 210,
  },
  subtitle: {
    color: COLORS.textSecondary,
    fontSize: FONT_SIZE.md,
    lineHeight: 23,
    maxWidth: 300,
    textAlign: 'center',
  },
  illustration: {
    alignItems: 'center',
    alignSelf: 'center',
    height: 178,
    justifyContent: 'flex-end',
    marginTop: SPACING[1],
    width: '100%',
  },
  plant: {
    alignItems: 'center',
    bottom: SPACING[3],
    flexDirection: 'row',
    gap: SPACING[1],
    left: SPACING[7],
    position: 'absolute',
  },
  leafTall: {
    backgroundColor: '#8FCBFF',
    borderBottomLeftRadius: RADIUS.full,
    borderBottomRightRadius: RADIUS.full,
    borderTopLeftRadius: RADIUS.full,
    height: 82,
    transform: [{ rotate: '-18deg' }],
    width: 22,
  },
  leafSmall: {
    backgroundColor: '#B5DFFF',
    borderBottomLeftRadius: RADIUS.full,
    borderBottomRightRadius: RADIUS.full,
    borderTopRightRadius: RADIUS.full,
    height: 58,
    transform: [{ rotate: '22deg' }],
    width: 22,
  },
  doctorAvatar: {
    alignItems: 'center',
  },
  doctorHead: {
    backgroundColor: '#FFC09B',
    borderColor: COLORS.primaryDark,
    borderRadius: RADIUS.full,
    borderWidth: 6,
    height: 70,
    marginBottom: -12,
    width: 70,
  },
  doctorBody: {
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    borderColor: COLORS.borderSoft,
    borderRadius: RADIUS.xl,
    borderWidth: 1,
    height: 92,
    justifyContent: 'center',
    width: 124,
    ...SHADOWS.sm,
  },
  tablet: {
    backgroundColor: '#316CA5',
    borderRadius: RADIUS.sm,
    bottom: SPACING[4],
    padding: SPACING[2],
    position: 'absolute',
    right: SPACING[10],
    transform: [{ rotate: '-8deg' }],
    width: 70,
    ...SHADOWS.sm,
  },
  tabletLine: {
    backgroundColor: '#C8E7FF',
    borderRadius: RADIUS.full,
    height: 6,
    marginBottom: SPACING[2],
  },
  tabletLineShort: {
    backgroundColor: '#EAF4FF',
    borderRadius: RADIUS.full,
    height: 6,
    width: 36,
  },
  plusBadge: {
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.full,
    bottom: SPACING[8],
    height: 34,
    justifyContent: 'center',
    position: 'absolute',
    right: SPACING[5],
    width: 34,
  },
  plusBadgeText: {
    color: COLORS.white,
    fontSize: FONT_SIZE.xl,
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: 25,
  },
  form: {
    gap: SPACING[3],
  },
  phoneMask: {
    color: COLORS.textMuted,
    fontSize: FONT_SIZE.xs,
    fontWeight: FONT_WEIGHT.medium,
  },
  termsRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: SPACING[3],
  },
  checkbox: {
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    borderColor: COLORS.border,
    borderRadius: RADIUS.xs,
    borderWidth: 1,
    height: 22,
    justifyContent: 'center',
    marginTop: 1,
    width: 22,
  },
  checkboxChecked: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  termsText: {
    color: COLORS.textSecondary,
    flex: 1,
    fontSize: FONT_SIZE.sm,
    lineHeight: 20,
  },
  termsLink: {
    color: COLORS.primary,
    fontWeight: FONT_WEIGHT.semibold,
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  formError: {
    color: COLORS.danger,
    fontSize: FONT_SIZE.sm,
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: 20,
  },
  dividerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: SPACING[3],
    marginTop: SPACING[1],
  },
  divider: {
    backgroundColor: COLORS.border,
    flex: 1,
    height: 1,
  },
  dividerText: {
    color: COLORS.textSecondary,
    fontSize: FONT_SIZE.sm,
  },
  socialRow: {
    flexDirection: 'row',
    gap: SPACING[3],
  },
  socialButton: {
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    borderColor: COLORS.border,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: SPACING[3],
    height: 54,
    justifyContent: 'center',
  },
  googleMark: {
    color: COLORS.primary,
    fontSize: FONT_SIZE.lg,
    fontWeight: FONT_WEIGHT.extrabold,
  },
  appleMark: {
    color: COLORS.textPrimary,
    fontSize: FONT_SIZE.lg,
    fontWeight: FONT_WEIGHT.extrabold,
  },
  socialText: {
    color: COLORS.textPrimary,
    fontSize: FONT_SIZE.md,
    fontWeight: FONT_WEIGHT.semibold,
  },
  footerText: {
    color: COLORS.textSecondary,
    fontSize: FONT_SIZE.md,
    textAlign: 'center',
  },
  footerLink: {
    color: COLORS.primary,
    fontWeight: FONT_WEIGHT.bold,
  },
})
