import {
  COLORS,
  COMPONENTS,
  FONT_SIZE,
  FONT_WEIGHT,
  RADIUS,
  SHADOWS,
  SPACING,
} from '@/constants/theme'
import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  content: {
    flexGrow: 1,
    justifyContent: 'space-between',
    overflow: 'hidden',
    paddingBottom: SPACING[7],
    paddingHorizontal: SPACING[6],
    paddingTop: SPACING[10],
  },
  backgroundCircle: {
    position: 'absolute',
    right: -96,
    top: -88,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: COLORS.primaryLight,
  },
  header: {
    alignItems: 'center',
    gap: SPACING[3],
  },
  logo: {
    width: 190,
    height: 58,
    resizeMode: 'contain',
  },
  tagline: {
    color: COLORS.textSecondary,
    fontSize: FONT_SIZE.sm,
    fontWeight: FONT_WEIGHT.medium,
    textAlign: 'center',
  },
  welcomeCard: {
    ...COMPONENTS.card,
    gap: SPACING[4],
    padding: SPACING[5],
  },
  illustration: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: COLORS.secondaryLight,
    borderRadius: RADIUS.xxl,
    height: 164,
    justifyContent: 'center',
    marginBottom: SPACING[2],
    width: '100%',
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    borderColor: COLORS.secondary,
    borderRadius: RADIUS.xxl,
    borderWidth: 3,
    height: 86,
    justifyContent: 'center',
    width: 86,
    ...SHADOWS.sm,
  },
  avatarFace: {
    color: COLORS.secondary,
    fontSize: FONT_SIZE.display,
    fontWeight: FONT_WEIGHT.extrabold,
    lineHeight: 42,
  },
  clipboard: {
    backgroundColor: COLORS.surface,
    borderColor: COLORS.borderSoft,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    bottom: SPACING[5],
    padding: SPACING[3],
    position: 'absolute',
    right: SPACING[8],
    width: 72,
    ...SHADOWS.sm,
  },
  clipboardLine: {
    backgroundColor: COLORS.primaryLight,
    borderRadius: RADIUS.full,
    height: 8,
    marginBottom: SPACING[2],
  },
  clipboardLineShort: {
    backgroundColor: COLORS.secondaryLight,
    borderRadius: RADIUS.full,
    height: 8,
    width: 38,
  },
  healthBadge: {
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.full,
    height: 48,
    justifyContent: 'center',
    left: SPACING[8],
    position: 'absolute',
    top: SPACING[5],
    width: 48,
    ...SHADOWS.sm,
  },
  healthBadgeText: {
    color: COLORS.white,
    fontSize: FONT_SIZE.xs,
    fontWeight: FONT_WEIGHT.bold,
  },
  title: {
    color: COLORS.textPrimary,
    fontSize: FONT_SIZE.xl,
    fontWeight: FONT_WEIGHT.extrabold,
    lineHeight: 28,
    textAlign: 'center',
  },
  subtitle: {
    color: COLORS.textSecondary,
    fontSize: FONT_SIZE.sm,
    lineHeight: 22,
    textAlign: 'center',
  },
  form: {
    gap: SPACING[3],
  },
  forgotPassword: {
    alignSelf: 'flex-end',
    color: COLORS.primary,
    fontSize: FONT_SIZE.xs,
    fontWeight: FONT_WEIGHT.semibold,
  },
  formError: {
    color: COLORS.danger,
    fontSize: FONT_SIZE.xs,
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: 18,
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  dividerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: SPACING[3],
  },
  divider: {
    backgroundColor: COLORS.borderSoft,
    flex: 1,
    height: 1,
  },
  dividerText: {
    color: COLORS.textMuted,
    fontSize: FONT_SIZE.xs,
  },
  socialRow: {
    flexDirection: 'row',
    gap: SPACING[3],
  },
  socialButton: {
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    borderColor: COLORS.border,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: SPACING[2],
    height: 48,
    justifyContent: 'center',
  },
  googleMark: {
    color: COLORS.primary,
    fontSize: FONT_SIZE.md,
    fontWeight: FONT_WEIGHT.extrabold,
  },
  appleMark: {
    color: COLORS.textPrimary,
    fontSize: FONT_SIZE.md,
    fontWeight: FONT_WEIGHT.extrabold,
  },
  socialText: {
    color: COLORS.textPrimary,
    fontSize: FONT_SIZE.sm,
    fontWeight: FONT_WEIGHT.semibold,
  },
  footer: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  footerText: {
    color: COLORS.textSecondary,
    fontSize: FONT_SIZE.sm,
  },
  footerLink: {
    color: COLORS.primary,
    fontSize: FONT_SIZE.sm,
    fontWeight: FONT_WEIGHT.bold,
  },
})
