import {
  COLORS,
  FONT_SIZE,
  FONT_WEIGHT,
  RADIUS,
  SHADOWS,
  SPACING,
} from '@/constants/theme'
import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  container: {
    backgroundColor: COLORS.secondary,
    borderRadius: RADIUS.xl,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 176,
    overflow: 'hidden',
    padding: SPACING[5],
    ...SHADOWS.md,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
  },
  eyebrow: {
    color: '#DDFBFD',
    fontSize: FONT_SIZE.xs,
    fontWeight: FONT_WEIGHT.medium,
    marginBottom: SPACING[2],
  },
  doctorName: {
    color: COLORS.white,
    fontSize: FONT_SIZE.md,
    fontWeight: FONT_WEIGHT.extrabold,
    lineHeight: 20,
  },
  specialty: {
    color: '#E9FEFF',
    fontSize: FONT_SIZE.xs,
    fontWeight: FONT_WEIGHT.medium,
    marginBottom: SPACING[4],
    marginTop: SPACING[1],
  },
  infoRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: SPACING[2],
    marginTop: SPACING[2],
  },
  infoText: {
    color: COLORS.white,
    fontSize: FONT_SIZE.xs,
    fontWeight: FONT_WEIGHT.semibold,
  },
  infoDot: {
    color: '#DDFBFD',
    fontSize: FONT_SIZE.xs,
    fontWeight: FONT_WEIGHT.bold,
  },
  side: {
    alignItems: 'center',
    justifyContent: 'space-between',
    marginLeft: SPACING[3],
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.lg,
    height: 78,
    justifyContent: 'flex-end',
    overflow: 'hidden',
    paddingTop: SPACING[2],
    width: 68,
  },
  avatarHair: {
    backgroundColor: COLORS.primaryDark,
    borderRadius: RADIUS.full,
    height: 44,
    position: 'absolute',
    top: SPACING[2],
    width: 44,
  },
  avatarFace: {
    backgroundColor: '#FFC09B',
    borderRadius: RADIUS.full,
    height: 34,
    marginBottom: -6,
    width: 34,
  },
  avatarCoat: {
    alignItems: 'center',
    backgroundColor: '#F6FBFF',
    borderTopLeftRadius: RADIUS.md,
    borderTopRightRadius: RADIUS.md,
    height: 34,
    justifyContent: 'center',
    width: 58,
  },
  detailsButton: {
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.full,
    height: 34,
    justifyContent: 'center',
    minWidth: 92,
    paddingHorizontal: SPACING[3],
  },
  detailsText: {
    color: COLORS.secondaryDark,
    fontSize: FONT_SIZE.xs,
    fontWeight: FONT_WEIGHT.bold,
  },
})
